### ISSUE TITLE
TypeError going to www only

### ISSUE THREAD

**Issue by paulshapiro** [treygriffith/connect-mongodb#13]
Hi there,

When I go to www.server.com instead of server.com, Express dumps with this:

```
Express
500 TypeError: Cannot call method 'toString' of undefined
at /home/peerbii/lib/node/.npm/connect-mongodb/0.2.2/package/lib/connect-mongodb.js:136:44
at [object Object]. (/home/.../lib/node/.npm/mongodb/0.9.2/package/lib/mongodb/collection.js:448:35)
at [object Object].emit (events.js:67:17)
at [object Object]. (/home/.../lib/node/.npm/mongodb/0.9.2/package/lib/mongodb/db.js:90:12)
at [object Object].emit (events.js:64:17)
at Socket. (/home/.../lib/node/.npm/mongodb/0.9.2/package/lib/mongodb/connection.js:82:16)
at Socket.emit (events.js:64:17)
at Socket._onReadable (net.js:665:31)
at IOWatcher.onReadable [as callback] (net.js:177:10)
```

Line 136 of connect-mongodb.js is 

```
      cb(null, JSON.parse(data.session.toString()));
```

Any ideas?

Thanks

**Comment by paulshapiro** [comment]
This goes away if I db.sessions.remove({})
