### ISSUE TITLE
npm install connect-mongodb failing

### ISSUE THREAD

**Issue by varunsrin** [treygriffith/connect-mongodb#17]
I'm running MongoDB 1.8.1,  Express 2.3.4, Mongoose 1.3.3 & I am unable to perform npm install connect-mongodb. The output I get is as follows: 

```
> mongodb@0.9.4-3 install /home/varun/simpleredir/node_modules/connect-mongodb/node_modules/mongodb
> bash ./install.sh

./install.sh: line 2: [: too many arguments
Not building native library for cygwin
make -C ./external-libs/bson
make[1]: Entering directory `/home/varun/simpleredir/node_modules/connect-mongodb/node_modules/mongodb/external-libs/bson'
rm -rf build .lock-wscript bson.node
node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.079s)
Waf: Entering directory `/home/varun/simpleredir/node_modules/connect-mongodb/node_modules/mongodb/external-libs/bson/build'
[1/9] cxx: bson.cc -> build/default/bson_1.o
[2/9] cxx: long.cc -> build/default/long_1.o
../long.cc: In member function ‘char* Long::toString(int32_t, char*)’:
../long.cc:251: warning: format ‘%lld’ expects type ‘long long int’, but argument 3 has type ‘int64_t’
../long.cc:254: warning: format ‘%llu’ expects type ‘long long unsigned int’, but argument 3 has type ‘int64_t’
../long.cc:258: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 3 has type ‘int64_t’
[3/9] cxx: objectid.cc -> build/default/objectid_1.o
[4/9] cxx: binary.cc -> build/default/binary_1.o
[5/9] cxx: code.cc -> build/default/code_1.o
[6/9] cxx: dbref.cc -> build/default/dbref_1.o
[7/9] cxx: timestamp.cc -> build/default/timestamp_1.o
../timestamp.cc: In member function ‘char* Timestamp::toString(int32_t, char*)’:
../timestamp.cc:247: warning: format ‘%lld’ expects type ‘long long int’, but argument 3 has type ‘int64_t’
../timestamp.cc:250: warning: format ‘%llu’ expects type ‘long long unsigned int’, but argument 3 has type ‘int64_t’
../timestamp.cc:254: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 3 has type ‘int64_t’
[8/9] cxx: local.cc -> build/default/local_1.o
[9/9] cxx_link: build/default/bson_1.o build/default/long_1.o build/default/objectid_1.o build/default/binary_1.o build/default/code_1.o build/default/dbref_1.o build/default/timestamp_1.o build/default/local_1.o -> build/default/bson.node
Waf: Leaving directory `/home/varun/simpleredir/node_modules/connect-mongodb/node_modules/mongodb/external-libs/bson/build'
'build' finished successfully (7.735s)
=== EXCEUTING TEST_BSON ===
node: ../src/node.cc:1212: ssize_t node::DecodeWrite(char*, size_t, v8::Handle<v8::Value>, node::encoding): Assertion `b[1] == 0' failed.
make[1]: *** [all] Aborted
make[1]: Leaving directory `/home/varun/simpleredir/node_modules/connect-mongodb/node_modules/mongodb/external-libs/bson'
make: *** [build_native] Error 2
npm ERR! error installing mongodb@0.9.4-3 Error: mongodb@0.9.4-3 install: `bash ./install.sh`
npm ERR! error installing mongodb@0.9.4-3 `sh "-c" "bash ./install.sh"` failed with 2
npm ERR! error installing mongodb@0.9.4-3     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing mongodb@0.9.4-3     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing mongodb@0.9.4-3     at ChildProcess.onexit (child_process.js:246:12)
npm ERR! error installing connect-mongodb@0.3.0 Error: mongodb@0.9.4-3 install: `bash ./install.sh`
npm ERR! error installing connect-mongodb@0.3.0 `sh "-c" "bash ./install.sh"` failed with 2
npm ERR! error installing connect-mongodb@0.3.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing connect-mongodb@0.3.0     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing connect-mongodb@0.3.0     at ChildProcess.onexit (child_process.js:246:12)
npm ERR! mongodb@0.9.4-3 install: `bash ./install.sh`
npm ERR! `sh "-c" "bash ./install.sh"` failed with 2
npm ERR! 
npm ERR! Failed at the mongodb@0.9.4-3 install script.
npm ERR! This is most likely a problem with the mongodb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls mongodb
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.35-28-server
npm ERR! command "node" "/usr/local/bin/npm" "install" "connect-mongodb"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/varun/simpleredir/npm-debug.log
npm not ok
```

**Comment by masylum** [comment]
you get the error installing the latest mongodb driver.
`Failed at the mongodb@0.9.4-3 install script`
Forward the issue to https://github.com/christkv/node-mongodb-native
