### ISSUE TITLE
no method toUTCString 

### ISSUE THREAD

**Issue by Charuru** [treygriffith/connect-mongodb#25]
I was on 0.3.0 and just updated to connect 1.5.2 and connect-mongodb 0.4.0

I'm getting this error:

```
    /Users/aaa/proj/node_modules/connect-mongodb/node_modules/connect/lib/utils.js:171

      if (obj.expires) pairs.push('expires=' + obj.expires.toUTCString());



                         ^


    TypeError: Object 5184000000 has no method 'toUTCString'
        at Object.serializeCookie (/Users/aaa/proj/node_modules/connect-mongodb/node_modules/connect/lib/utils.js:171:56)
        at Object.serialize (/Users/aaa/proj/node_modules/connect-mongodb/node_modules/connect/lib/middleware/session/cookie.js:113:18)
        at ServerResponse.writeHead (/Users/aaa/proj/node_modules/express/node_modules/connect/lib/middleware/session.js:264:46)
        at ServerResponse._implicitHeader (http.js:787:8)
        at ServerResponse.end (http.js:651:10)
        at next (/Users/aaa/proj/node_modules/express/node_modules/connect/lib/http.js:169:13)
        at /Users/aaa/proj/node_modules/express/node_modules/connect/lib/middleware/session.js:322:9
        at /Users/aaa/proj/node_modules/express/node_modules/connect/lib/middleware/session.js:322:9
        at /Users/aaa/proj/node_modules/express/node_modules/connect/lib/middleware/session.js:332:11
        at /Users/aaa/proj/node_modules/connect-mongodb/lib/connect-mongodb.js:166:7
```

Reverting back to 0.3.0 for now.

**Comment by masylum** [comment]
delete the contents of your sessions collection and try again.
Post the contents of your npm ls so I can see which versions are you using.

**Comment by masylum** [comment]
try again with the latest release and post the feedback :)

**Comment by masylum** [comment]
no answer since last week so I close the ticket.
Reopen it if something is wrong.

**Comment by aronwoost** [comment]
I can confirm this one. Seams to have something to do with the size of maxAge

`cookie: {maxAge: 60000 * 60 * 24 * 365}` leads to the error above

`cookie: {maxAge: 60000 * 60 * 24}` works fine
