### ISSUE TITLE
Keeping getting this error if tried to access from external IP

### ISSUE THREAD

**Issue by motionworks** [treygriffith/connect-mongodb#26]
TypeError: Cannot read property 'expires' of undefined
    at MongoStore.createSession (/node_modules/connect/lib/middleware/session/store.js:51:28)
    at /node_modules/express/node_modules/connect/lib/middleware/session.js:340:15
    at /node_modules/connect-mongodb/lib/connect-mongodb.js:161:9
    at [object Object].<anonymous> (/node_modules/connect-mongodb/node_modules/mongodb/lib/mongodb/collection.js:669:5)
    at [object Object].emit (events.js:67:17)
    at [object Object].<anonymous> (/node_modules/connect-mongodb/node_modules/mongodb/lib/mongodb/connections/server.js:78:12)
    at [object Object].emit (events.js:64:17)
    at Socket.<anonymous> (/node_modules/connect-mongodb/node_modules/mongodb/lib/mongodb/connection.js:89:16)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:673:31)

And this one : 

SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)
    at /var/www/TGV/node_modules/connect-mongodb/lib/connect-mongodb.js:133:23
    at [object Object].<anonymous> (/var/www/TGV/node_modules/connect-mongodb/node_modules/mongodb/lib/mongodb/collection.js:764:5)
    at [object Object].emit (events.js:67:17)
    at [object Object].<anonymous> (/var/www/TGV/node_modules/connect-mongodb/node_modules/mongodb/lib/mongodb/connections/server.js:88:12)
    at [object Object].emit (events.js:64:17)
    at Socket.<anonymous> (/var/www/TGV/node_modules/connect-mongodb/node_modules/mongodb/lib/mongodb/connection.js:94:16)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:673:31)
    at IOWatcher.onReadable [as callback](net.js:177:10)

**Comment by masylum** [comment]
delete the contents of your sessions collection and try again.
Post the contents of your `npm ls` so I can see which versions are you using.

**Comment by motionworks** [comment]
âââ async@0.1.9
âââ¬ bcrypt@0.2.3
â âââ nodeunit@0.5.1
âââ¬ connect@1.4.6
â âââ mime@1.2.2
â âââ qs@0.1.0
âââ connect-auth@0.2.2
âââ¬ connect-mongodb@0.4.0
â âââ mongodb@0.9.4-5
âââ¬ cron@0.1.2
â âââ nodeunit@0.5.1
âââ¬ everyauth@0.2.11
â âââ oauth@0.9.0
â âââ openid@0.1.8
â âââ restler@0.2.1
â âââ¬ xml2js@0.1.8
â   âââ sax@0.1.4
âââ¬ express@2.3.11
â âââ connect@1.4.6
â âââ mime@1.2.2
â âââ qs@0.1.0
âââ hashlib@1.0.0
âââ jade@0.12.2
âââ¬ mongoose@1.4.0
â âââ hooks@0.1.7
âââ mongoose-auth@0.0.11
âââ¬ mongoose-types@1.0.3
â âââ¬ mongoose@1.4.0
â   âââ hooks@0.1.7
âââ request@1.9.5
âââ socket.io@0.6.18
âââ underscore@1.1.6

Do we need to install all these npms globally?

**Comment by masylum** [comment]
try again with the latest release and post the feedback :)

**Comment by masylum** [comment]
no answer since last week so I close the ticket.
Reopen it if something is wrong.
