### ISSUE TITLE
TypeError: Object [object Object] has no method 'isConnected'

### ISSUE THREAD

**Issue by sethml** [treygriffith/connect-mongodb#28]
With the HEAD version of connect-mongodb (https://github.com/masylum/connect-mongodb/commit/fdbe0ff4bf9465f7bfa55f106b2176d3cfd3df79), trying to use it in a replicated mongo setup, I get the following error on app startup:

```
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object [object Object] has no method 'isConnected'
    at new MongoStore (/Users/seth/development/service/node_modules/connect-mongodb/lib/connect-mongodb.js:151:21)
    at HTTPServer.<anonymous> (/Users/seth/development/service/app.js:235:12)
    at HTTPServer.configure (/Users/seth/development/service/node_modules/express/lib/http.js:484:52)
    at Object.<anonymous> (/Users/seth/development/service/app.js:219:5)
    at Module._compile (module.js:407:26)
    at Object..js (module.js:413:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at Array.<anonymous> (module.js:426:10)
    at EventEmitter._tickCallback (node.js:126:26)
```

**Comment by sethml** [comment]
https://github.com/masylum/connect-mongodb/pull/29
