### ISSUE TITLE
Doesn't work with node.js v0.4.9

### ISSUE THREAD

**Issue by murvinlai** [treygriffith/connect-mongodb#30]
I just update node to 0.4.9 and when i do this:
app = require('express').createServer(

```
     express.cookieParser(),
      // Parses x-www-form-urlencoded request bodies (and json)
      express.bodyParser(),
      express.session({ secret: cfg.wiki_session_secret,
            store:new MongoStore({  
                        dbname: 'mydatabase',
                        host: '127.0.0.1',
                        port: 27017
                 })
        })
),
```

I got this error: 

Express
500 TypeError: Cannot call method 'findOne' of null

```
at MongoStore.get (/usr/local/lib/node/.npm/connect-mongodb/1.0.0beta/package/lib/connect-mongodb.js:96:15)
at Object.session [as handle] (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/middleware/session.js:318:11)
at next (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/http.js:204:15)
at Object.bodyParser [as handle] (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/middleware/bodyParser.js:59:61)
at next (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/http.js:204:15)
at Object.cookieParser [as handle] (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/middleware/cookieParser.js:44:5)
at next (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/http.js:204:15)
at Object.handle (/usr/local/lib/node/.npm/express/2.4.0/package/lib/http.js:85:5)
at next (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/http.js:204:15)
at HTTPServer.handle (/usr/local/lib/node/.npm/connect/1.5.1/package/lib/http.js:217:3)
```

I think it doesn't work for v0.4.9

**Comment by murvinlai** [comment]
it is the _collection is null.  at line 96 of connect-mongodb.  
Not sure why it is null though

**Comment by masylum** [comment]
The 1.0.0beta is not stable yet, use 0.4.0 instad

**Comment by caiges** [comment]
Why are unstable releases being pushed to npm?

**Comment by masylum** [comment]
Why not? There is people that like the edge.
And these people report bugs so it helps to get the release stable.

**Comment by masylum** [comment]
try again with the latest release and post the feedback :)

**Comment by caiges** [comment]
In your defense ... it was labeled beta. ;) I just spent two hours with it last night == frustration.  I'll test the latest and report.  THX

**Comment by masylum** [comment]
no answer since last week so I close the ticket.
Reopen it if something is wrong.

**Comment by nairboon** [comment]
still not working in 1.0.0rc2

**Comment by yanek1988** [comment]
I spent few hours with some problems with connect-mongodb. After reading this issue I installed version 0.4.0 and problems gone. I think in npm should by stable version.

**Comment by masylum** [comment]
please let me know whichs problems did you had with the latest one. Should be stable.

**Comment by yanek1988** [comment]
The same like @murvinlai:
Express
500 TypeError: Cannot call method 'findOne' of null
...

**Comment by masylum** [comment]
I need more info in order to fix the bug. Could you please investigate a little bit more? 1.0.0 should get the collection.

https://github.com/masylum/connect-mongodb/blob/master/lib/connect-mongodb.js#L33

Are you getting to that line? If not, let me know why.
