### ISSUE TITLE
error trying to use sessions with replica sets

### ISSUE THREAD

**Issue by pkyeck** [treygriffith/connect-mongodb#38]
hi. i'm trying to use connect-mongodb (and express) with replica sets and authentication but get the following error:

``` javascript
Cannot call method 'findOne' of null
    at MongoStore.get (/home/phil/Dokumente/www/node_modules/connect-mongodb/lib/connect-mongodb.js:95:15)
    at Object.session (as handle)  (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/middleware/session.js:319:11)
    at next (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/http.js:201:15)
    at Object.cookieParser (as handle) (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:44:5)
    at next (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/http.js:201:15)
    at Object.methodOverride (as handle) (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:35:5)
    at next (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/http.js:201:15)
    at Object.bodyParser (as handle) (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:59:61)
    at next (/home/phil/Dokumente/www/node_modules/express/node_modules/connect/lib/http.js:201:15)
    at Object.handle (/home/phil/Dokumente/www/node_modules/express/lib/http.js:84:5)
```

my code looks like this:

``` javascript
app.configure(function(){
  app.set('views', __dirname + '/views');
  app.set('view engine', 'ejs');
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser());
  app.use(express.session({
    cookie: {maxAge: 60000 * 20}, // 20 minutes
    secret: 'foo',
    store: new mongoStore({
      host: '192.168.2.99',
      port: [27017, 27018, 27019],
      dbname: 'testdb',
      username: 'testdb_user',
      password: 'secret'
    })
  }));
  app.use(app.router);
  app.use(express.static(__dirname + '/public'));
});
```

any advice?

**Comment by CarlLee** [comment]
I found this issue when I was reading this project's source code.
This is mainly because mongodb connection was not yet established(because in this project it establish connection with mongodb asynchronously), by the time your session data is being used(set/get/length etc.).
Everything will work once the connection is established, so basically you will just miss first a few requests, after that everything will be just fine.

If you're still not comfortable with this, you can do this:

``` javascript
app.configure(function(){
  app.set('views', __dirname + '/views');
  app.set('view engine', 'ejs');
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser());
  app.use(express.session({
    cookie: {maxAge: 60000 * 20}, // 20 minutes
    secret: 'foo',
    store: new mongoStore({
      host: '192.168.2.99',
      port: [27017, 27018, 27019],
      dbname: 'testdb',
      username: 'testdb_user',
      password: 'secret'
    }, function(){
    // Everythin will work fine inside this callback function
    app.use(app.router);
  })
  }));
  app.use(express.static(__dirname + '/public'));
});
```

**Comment by pkyeck** [comment]
ah, thanks for the sample. will try and change my code accordingly ...

**Comment by Philmod** [comment]
It doesn't work for me...

pkyeck> does it for you?

**Comment by pkyeck** [comment]
can't remember if it worked for me or not ... but checked my current code and it looks something like this:

``` javascript

// express stuff ...
var mongo = require('mongoose');

var conf = exports.conf = {
    db: {
        db: '<dbname>',
        host: 'xx.xx.xx.xx',
        host2: 'xx.xx.xx.xx',
        username: '<username>',
        password: '<password>',
        clear_interval: 360 // in seconds
    }
};

var mongoUrl  = 'mongodb://'+conf.db.username+':'+conf.db.password+'@'+conf.db.host+'/'+conf.db.db+',';
mongoUrl += 'mongodb://'+conf.db.host2+'/'+conf.db.db+',';
mongoUrl += 'mongodb://'+conf.db.host2+':27018/'+conf.db.db;

mongo.connectSet(mongoUrl, function (err) {
    if (err) {
        console.log("could not connect to DB: " + err);
    }
});

mongo.connection.on('open', function () {
    console.log("MONGO conn open ... ");

    //
    console.log("express session w/ MongoStore");
    app.use(express.session({
        secret: '<SECRET>',
        cookie: {
            maxAge: 60000 * 20 // 20 minutes
        },
        store: new MongoStore({
            db: mongo.connection.db
        })
    }));

    app.use(app.router);

    //
    app.listen(3000);
    console.log("Express server listening on port %d in %s mode", app.address().port, app.settings.env);

    // Routes
    // my routes: ... require('./controllers/index')(app, middle);
});


app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'ejs');

    app.set('dataDir', __dirname + '/public/data')

    // connect-form settings
    app.use(form({ keepExtensions: true }));

    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());

    app.use(express.static(__dirname + '/public'));
});

```
