### ISSUE TITLE
Error installing connect-mongodb

### ISSUE THREAD

**Issue by omicronlab** [treygriffith/connect-mongodb#39]
I'm getting this error while trying to install connect-mongodb

npm install connect-mongodb

npm ERR! error installing connect-mongodb@1.0.0 Error: shasum check failed for /var/folders/kx/lq9mryjn1qsd84kzy9wy9fz80000gn/T/npm-1318079623785/1318079623803-0.30375908222049475/tmp.tgz
npm ERR! error installing connect-mongodb@1.0.0 Expected: 1061dbf18f5f4a00f6da52a0c9eab11e70620bfc
npm ERR! error installing connect-mongodb@1.0.0 Actual:   c3d6a2bec2379bf568ba0b2ae495b093dae5f85c
npm ERR! error installing connect-mongodb@1.0.0     at /usr/local/lib/node_modules/npm/lib/utils/sha.js:25:20
npm ERR! error installing connect-mongodb@1.0.0     at [object Object].<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/sha.js:49:5)
npm ERR! error installing connect-mongodb@1.0.0     at [object Object].emit (events.js:61:17)
npm ERR! error installing connect-mongodb@1.0.0     at afterRead (fs.js:878:12)
npm ERR! error installing connect-mongodb@1.0.0     at wrapper (fs.js:245:17)
npm ERR! Error: shasum check failed for /var/folders/kx/lq9mryjn1qsd84kzy9wy9fz80000gn/T/npm-1318079623785/1318079623803-0.30375908222049475/tmp.tgz
npm ERR! Expected: 1061dbf18f5f4a00f6da52a0c9eab11e70620bfc
npm ERR! Actual:   c3d6a2bec2379bf568ba0b2ae495b093dae5f85c
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/sha.js:25:20
npm ERR!     at [object Object].<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/sha.js:49:5)
npm ERR!     at [object Object].emit (events.js:61:17)
npm ERR!     at afterRead (fs.js:878:12)
npm ERR!     at wrapper (fs.js:245:17)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 11.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "connect-mongodb"
npm ERR! cwd /Volumes/work/Projects/NodeApps/madblog
npm ERR! node -v v0.4.11
npm ERR! npm -v 1.0.30
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Volumes/work/Projects/NodeApps/madblog/npm-debug.log
npm not ok

**Comment by omicronlab** [comment]
Weird! After a few hours it is working perfectly
